<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[myMethod 1 is Running]]>
    </line>
    <line>
      <![CDATA[TC Passed Successfully]]>
    </line>
    <line>
      <![CDATA[Name of Test method completed suceess is myMethod1]]>
    </line>
    <line>
      <![CDATA[Test Case Failed please check again]]>
    </line>
    <line>
      <![CDATA[Name of Test method failed is myMethod2]]>
    </line>
    <line>
      <![CDATA[test case skipped, please check dependant method]]>
    </line>
    <line>
      <![CDATA[Name of Test method skipped is myMethod3]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-05T21:48:07 IST" name="Default suite" finished-at="2022-07-05T21:48:08 IST" duration-ms="266">
    <groups>
    </groups>
    <test started-at="2022-07-05T21:48:07 IST" name="Default test" finished-at="2022-07-05T21:48:08 IST" duration-ms="266">
      <class name="Listners.MyTest">
        <test-method signature="myMethod1()[pri:0, instance:Listners.MyTest@67c27493]" started-at="2022-07-05T21:48:08 IST" name="myMethod1" finished-at="2022-07-05T21:48:08 IST" duration-ms="38" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[myMethod 1 is Running]]>
            </line>
            <line>
              <![CDATA[TC Passed Successfully]]>
            </line>
            <line>
              <![CDATA[Name of Test method completed suceess is myMethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod1 -->
        <test-method signature="myMethod2()[pri:0, instance:Listners.MyTest@67c27493]" started-at="2022-07-05T21:48:08 IST" name="myMethod2" finished-at="2022-07-05T21:48:08 IST" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Listners.MyTest.myMethod2(MyTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Case Failed please check again]]>
            </line>
            <line>
              <![CDATA[Name of Test method failed is myMethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod2 -->
        <test-method signature="myMethod3()[pri:0, instance:Listners.MyTest@67c27493]" started-at="2022-07-05T21:48:08 IST" name="myMethod3" finished-at="2022-07-05T21:48:08 IST" depends-on-methods="Listners.MyTest.myMethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MyTest.myMethod3()[pri:0, instance:Listners.MyTest@67c27493] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MyTest.myMethod3()[pri:0, instance:Listners.MyTest@67c27493] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[test case skipped, please check dependant method]]>
            </line>
            <line>
              <![CDATA[Name of Test method skipped is myMethod3]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod3 -->
      </class> <!-- Listners.MyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
